Repository hassio-addons/addon-base, pull requests merged in 2022-06, with the labels that each got.

#184 ⬆️ Upgrades Alpine Linux to 3.16.0
  base/Dockerfile
  base/build.yaml
Labels: dependencies, major

#176 Upgrade s6-overlay from 2.2.0.3 to 3.1.0.1
  base/Dockerfile
  base/rootfs/etc/cont-finish.d/99-message.sh
  base/rootfs/etc/cont-init.d/00-banner.sh
  base/rootfs/etc/cont-init.d/01-log-level.sh
  base/rootfs/usr/bin/service
Labels: dependencies, major

#185 Provide more defaults
  base/Dockerfile
Labels: enhancement

#186 Do not create old style S6 folders
  base/Dockerfile
Labels: maintenance

#187 ⬆️ Upgrades s6-overlay to v3.1.1.0
  base/Dockerfile
Labels: dependencies

#188 ⬆️ Upgrades s6-overlay to v3.1.1.1
  base/Dockerfile
Labels: dependencies
