Repository hassio-addons/addon-base, pull requests merged in 2023-03, with the labels that each got.

#216 ⬆️ Upgrades curl to 7.88.1-r0
  base/Dockerfile
Labels: dependencies

#217 Configure Renovate
  base/Dockerfile
Labels: ci, dependencies

#218 Add Renovate configuration
  .github/renovate.json
Labels: ci, dependencies

#220 Fix subfolder structure in Renovate regex managers
  .github/renovate.json
Labels: ci

#226 Remove dependabot
  .github/dependabot.yaml
Labels: maintenance

#233 Fix superfluous v in s6-overlay versioning
  .github/renovate.json
  base/Dockerfile
Labels: bugfix
